version: 0.2
phases:
  build:
    commands:
      - npm install -g yarn
      - yarn
  post_build:
    commands:
      - echo "Release_ID"
artifacts:
  name: "build-output"
  files:
    - "**/*"
reports:
  test-report:
    files:
      - 'junit.xml'
    file-format: 'JUNITXML'
  coverage-report:
    files:
      - 'coverage/clover.xml'
    file-format: 'CLOVERXML'
