version: 0.2
phases:
  
  build:
    commands:
      - node --version
      - npm install -g yarn
      - yarn
      - mvn clean install
  post_build:
    commands:
      - echo "#{codepipeline.PipelineExecutionId}"
      - echo $CUSTOM_VAR1
artifacts:
  name: "build-output"
  files:
    - "**/*"
reports:
  test-report:
    files:
      - 'junit.xml'
    file-format: 'JUNITXML'
  coverage-report:
    files:
      - 'coverage/clover.xml'
    file-format: 'CLOVERXML'
