name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-TestGitHubActions-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
      - image:linux-5.0
      - instance-size:small
    steps:
      - run: echo "Hello World BUILD FROM SELF-HOST GITHUB ACTIONS RUNNERsss!!!!"
      
  hern-test:
    runs-on:
      - codebuild-TestGitHubActions-${{ github.run_id }}-${{ github.run_attempt }}
      #- image:linux-5.0
      #- instance-size:small
    steps:
      - name: Test
        run: echo "hello world hearn"

  hern-two:
    runs-on:
      - codebuild-TestGitHubActions-${{ github.run_id }}-${{ github.run_attempt }}
      - image:linux-5.0
      #- instance-size:small
    steps:
      - name: Test
        run: echo "hello world hearn" && sleep 10
      

  pr-build-ui:
    runs-on:
      - codebuild-TestGitHubActions-${{ github.run_id }}-${{ github.run_attempt }}
      - image:linux-lambda-nodejs20
      - instance-size:2gb
    steps:
      - name: Test
        run: echo "hello world pr-build-ui"
